# Generated by Django 3.1.14 on 2022-06-24 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20220624_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonelementtype',
            name='pokemon_evolution',
        ),
        migrations.AddField(
            model_name='pokemonelementtype',
            name='evolution',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon'),
            preserve_default=False,
        ),
    ]
