# Generated by Django 3.1.14 on 2022-06-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_auto_20220624_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='element_type',
        ),
        migrations.DeleteModel(
            name='PokemonElementType',
        ),
    ]
