# Generated by Django 3.1.14 on 2022-06-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_pokemon_next_evolution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='next_evolution',
            new_name='previous_evolution',
        ),
    ]
